---
abstract: A simple filter for client and server HTTP contexts
author:
- Nicholas Perez <nperez@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.091260
license: gpl
name: POE-Filter-SimpleHTTP
requires:
  Compress::Zlib: '2.012'
  LWP: '5.822'
  Moose: '0.79'
  Regexp::Common: '2.122'
  Test::More: '0'
  UNIVERSAL::isa: '1.01'
  URI: '1.37'
  perl: 5.10.0
resources:
  repository: git://github.com/nperez/pfsh.git
version: '0.091700'
